---
short_title: "Reportes"
output: 
  html_document:
    css: 
      - https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css
      - ../style.css
    template: reportes-template.html
    theme: null
    self_contained: false
params:
  reportes: "`r list()`"
---

```{r, results='asis'}
library(htmltools)
library(magrittr)
render_reporte <- function(x){
  div(class = "reporte-card py-5", 
      a(href = x$href, 
        h2(class = "reportes-title", x$title), 
        p(class = "reporte-card-subtitle lead", x$subtitle), 
        p(class = "reporte-card-snippet", x$desc)
        )
      )
}
```


```{r, results='as.is'}

d <- div()
 
for(i in 1:length(params$reportes)){
  d <- tagAppendChild(d, render_reporte(params$reportes[[i]]))
}

d

```

<!--
<div class="reporte-card py-5">
<h2 class="reporte-card-title">Diferencias entre ciudadanos revisores</h2>
<p class="reporte-card-subtitle lead">Segundo reporte - 4 Jun, 2018 8:00a.m.</p>
<p class="reporte-card-snippet">Las ratas de aceptacion/rejection son similares lo que indica que los resultados seran confiables</p>
</div>-->

<div class="sharethis-inline-share-buttons py-5" id="share" data-description="data-description"></div>
<!--reportes:
  - title: Transparencia, ese es el nombre del juego
    subtitle: "Segundo reporte - 4 Jun, 2018 7:00p.m."
    href: segundo-reporte-revision-e14
    desc: "tbd"
  - title: Calentando motores
    subtitle: "Primer reporte - 3 Jun, 2018 9:30a.m."
    href: primer-reporte-revsion-e14
    desc: "Ha pasado solo un día desde que que se lanzó esta iniciativa ciudadana y la respuesta ha sido increíble. Entre todos ya hemos revisado más de 1,300 que equivalen aproximadamente al 1.3% del total." -->