---
title: "Reporte revision formularios E-14"
author: "Fernando Cagua"
date: "6/3/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(magrittr)
```

```{r}
e14 <- readr::read_csv(file = "e14-main-form.csv") %>%
  dplyr::filter(nota != "666" | is.na(nota)) %>%
  tidyr::separate(Timestamp, c("t", "z"), sep = " GMT") %>%
  dplyr::mutate(z = paste0(z, "00"), 
                date = paste(t, z), 
                date = as.POSIXct(date, format = "%Y/%m/%d %I:%M:%S %p %z"))
```

```{r basic-statistics}
per_id <- e14 %>%
  dplyr::group_by(id) %>%
  dplyr::summarise(n = n())

rate <- nrow(e14) /(as.numeric(max(e14$date)) - as.numeric(min(e14$date))) / 1000
```

```{r export-json}
list(max_contribution_user = max(per_id$n), 
     mean_contribution_user = median(per_id$n), 
     rate = rate, 
     min_date = as.numeric(min(e14$date)) * 1000, 
     max_date = as.numeric(max(e14$date)) * 1000,
     n_submissions = nrow(e14)) %>%
  jsonlite::toJSON()
```



